### ISSUE TITLE
LOS20 - Not able to open Android Auto

### ISSUE THREAD

**Issue by hkfuertes** [Nitsuya/AADisplay#1]
Maybe I'm doing something wrong... but I have a fresh copy of LOS20 without the Gapps, I install Magisk, LSposed, this app, everything is in green (the app tells so), but when I connect the device to the headunit (the emulator for now) I get a message saying that there is no app installed that can handle this accessory (I don't know the exact words...)

Do I need GAPPS?

**Comment by Nitsuya** [comment]
需要gapps,保证你能够正常连接AA,再使用该应用.
