### ISSUE TITLE
Buttons stop responding on resume

### ISSUE THREAD

**Issue by iampwd** [Nitsuya/AADisplay#10]
All AADisplay buttons stop responding after I use the car buttons to go other car apps or settings and then go back to android auto and AADisplay. The acutal app opened in AADisplays "app window" still works but I can't use any of the taskbar buttons. 

AAD 0.15#12.4+
System Version 14(API 34)
LSPosed 1.10.0 (7068)
AA 12.7.643414

Edit:
If I press any button marked as 1 I leave Android auto but then when I go back to Android auto all buttons marked as 2 have stopped working. 

![Screenshot](https://github.com/user-attachments/assets/46a294c4-6188-4df9-aadc-fa745d2e735c)

**Comment by Nitsuya** [comment]
未理解你的描述，请提供更加详细的操作步骤和图片，或操作视频。

**Comment by Nitsuya** [comment]
1. 这样操作后，信号和电量位置打开通知栏是否也会失效？

2.不使用AAD，是否也会失效？

目前未遇到其他人反馈该问题。

**Comment by iampwd** [comment]
Today it's working, must have been a problem with my phone. If it comes back I will try to get logs.
