### ISSUE TITLE
升级AA 12.8 后失失去dpi 修改功能 | dpi function not working after upgrading to AA 12.8

### ISSUE THREAD

**Issue by ertmuirm** [Nitsuya/AADisplay#11]
AA Display still works, but dpi changing functionality has stopped working

**Comment by Nitsuya** [comment]
等待修复。

**Comment by Nitsuya** [comment]
已修复!

**Comment by ertmuirm** [comment]
Thank you!

**Comment by Nitsuya** [comment]
似乎还存在问题。

**Comment by ertmuirm** [comment]
Yes issue still unresolved, unfortunately

**Comment by Nitsuya** [comment]
似乎google开始了新的阻止应用！ 
DPI在HUD上可以生效，但是非开发者模式下不生效，可能需要更长的时间去找hook点。
头痛。

**Comment by ertmuirm** [comment]
谢谢你的努力！
我开启了开发者模式，但dpi 功能再AA 12.8上还是不能生效，你成功的生效了吗？

**Comment by Nitsuya** [comment]
这个开发者模式指的协议上的开发者模式，可能早期手机上的也生效，后面Google关闭了

**Comment by Nitsuya** [comment]
已修复!!
