### ISSUE TITLE
I see the controls on the left but the app on the right in android auto is black

### ISSUE THREAD

**Issue by ne0YT** [Nitsuya/AADisplay#12]
when I press the buttons smh soemtimes it takes up half of the screen showign my phones screen but touch doesnt work correctly and it never works fullscreen.

screen2auto works wihtout those issues, but I think this should be better in the end..

**Comment by Nitsuya** [comment]
**装上你喜爱的启动器并在AAD的设置中填写包名!!!!!!**

正常情况下,手机侧的Mirror是支持触摸的,应该是在VirtualDisplay没有显示应用,所以你感知不到.
触摸空白区域退出Mirror,
半屏是因为我只想让手机竖屏, 因为车机是横屏的, 所以只能等比显示. 
除非车机是竖屏的,但我并没有适配,会导致最近应用的位置被挤压的看不见.

**Comment by ne0YT** [comment]
I see :)

I tried now with my launcher:
(Niagara Launcher)
bitpit.launcher
and this works generally.
but some things don't work like for example:
- I cannot use the on-screen keyboard in the launcher to search apps
- some apps icons are extremely big in the launcher on the car display while most look normal.
- is there an option to enable the notification Bar?
- some apps cannot be opened on the car display, when they were open already (whatsapp for example)
- it would be nice to auto-close the app on-disconnect.

maybe (I'm not sure, maybe some issues can still be fixed otherwise) it would work better to mirror the main screen while setting it's resolution using root similar to how screen2auto does it?

**Comment by ne0YT** [comment]
oh.. and do you know if someome is continuing lsposed?

**Comment by ne0YT** [comment]
before you ask why I'm switching..
S2A has major issues when switching back and forth between maps and S2A.. very often leading to a non-responsive/black S2A while your app keeps working always.

**Comment by Nitsuya** [comment]
这个做法和S2A完全不一样,它是Mirror手机屏幕,修改分辨率和DPI. 这样会导致手机连接后设备很难使用并且无法熄屏.
我的应用使用的是VirtualDisplay, 相当于另外一块屏幕, 只不过它是虚拟的.

---

1.键盘在可以设置在手机或虚拟屏显示, 有的rom可能虚拟屏显示不生效.

2.一些应用使用Application Context绘制UI导致显示过大, 但是这是应用开发者的问题, 我已经尝试在应用完全死亡的情况下, 从虚拟屏栈启动应用时去修复它, 这类应用请不要通过最近应用切换屏幕栈!  额外还有些应用反射获取状态栏高度导致应用过高.

3.并没有通知栏, 因为aosp并不支持.

4.通过最近应用左右滑动应用切换所在的屏幕栈.

5.断开时会进入倒计时销毁, 销毁时会完全杀死虚拟屏上的所有应用!

---

这个应用和它的前身大概在3年前我就写好了, 但是我并没有开源, 只在中国地区和朋友分享, 因为我们的网络并不支持Google服务和地图相关的东西. 我也用过S2A, 觉得很难用, 所以才有了AAD.

另外Android Auto 在10.X的版本就开始支持原生应用, 也是通过VirtualDisplay实现的, 需要配置Prop参数可以开启, 虽然可以全屏但是也很难用!!!

**Comment by ne0YT** [comment]
1. thank you for telling me :), for me it's fixable by changing the settings.
2. thank you for all the additional info, I will tell the creator of the launcher. maybe he will fix it 👍 
5. is it possible to adjust this timer?
6. yes.. I mean mainly the lack of the status Bar makes it worse otherwise your solution is much more stable and it's very cool how you made the controls on the left of the Android-Auto Bar. Google Maps actually works perfectly with this.

thank you a lot for this cool app!

**Comment by Nitsuya** [comment]
2. 需要设置VirtualDisplay DPI 才能修复显示不正常的应用.
3. 设置中可以调整销毁时间.
4. AOSP的功能就是这样的.


如果你是开发者, 看过一些AOSP的代码就能明白.
