### ISSUE TITLE
闪退问题，么么

### ISSUE THREAD

**Issue by mathlabroom** [Nitsuya/AADisplay#13]
删除日志文件

**Comment by Nitsuya** [comment]
追加所有版本信息和报错大概时间点。

**Comment by mathlabroom** [comment]
![Screenshot_2024-11-02-17-42-40-541_com google android projection gearhead](https://github.com/user-attachments/assets/59a62d32-59b0-4cf5-8103-fb2747a4564f)

**Comment by mathlabroom** [comment]
删除日志文件
这是清空日志后，重新闪退的日志

**Comment by Nitsuya** [comment]
Crash unexpectedly: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

不要用mod的LSP。

**Comment by Nitsuya** [comment]
查看 #9 相同的问题
