### ISSUE TITLE
App crash when I click the gear-icon (settings)

### ISSUE THREAD

**Issue by ne0YT** [Nitsuya/AADisplay#14]
I reinstalled the app and now after enabling and rebooting I cannot open the settings inside the app anymore, it instantly crashes when pressing the gear-icon.

**Comment by Nitsuya** [comment]
发报错日志。

**Comment by ne0YT** [comment]
已清理日志。

**Comment by Nitsuya** [comment]
提供LSP中的AAD报错日志!!

**Comment by ne0YT** [comment]
how do it do that?

**Comment by Nitsuya** [comment]
这不在我的回答范围内。需要你自行学习。

**Comment by ne0YT** [comment]
I really don't understand what you mean with LSP? do you mean lsposed?

**Comment by ne0YT** [comment]
已清理日志。

**Comment by Nitsuya** [comment]
Crash unexpectedly: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported！！！！

不要用LSP_MOD的版本，相关的Issues已经很多了！！！！

这不应该由我解决！！！！ 更换其他叉子分支！！！

**Comment by ne0YT** [comment]
thank you
