### ISSUE TITLE
running app with floating widget

### ISSUE THREAD

**Issue by ne0YT** [Nitsuya/AADisplay#15]
I have an app (Cam Sam) which creates a widget which floats on top of other apps. But also when launching the app from the car-display it will open there, but the floating widget will always launch on the main phone-display.
Maybe there's some kind of workaround for this?

And is there a possibility to start other apps automatically, besides the primary (launcher) app?

**Comment by Nitsuya** [comment]
1. [#12](https://github.com/Nitsuya/AADisplay/issues/12#issuecomment-2451563043) 第3条已回答悬浮窗问题.

2. 安装一个支持在启动时延迟打开设定应用的启动器. 比如AAD默认填写的启动器, 但是它只支持中文和一些本地化. 该问题并不在我的解答范围内.

叼.
