### ISSUE TITLE
[Question / feature request] - custom quick launcher "maps" instead of "phone"

### ISSUE THREAD

**Issue by ne0YT** [Nitsuya/AADisplay#17]
I'm sorry to ask so many questions..

but what really would be nice.. is to replace the phone-button with another app (I would love to have a Button opening Google Maps)
can I smh send you crypto?

**Comment by ne0YT** [comment]
It's not really needed

**Comment by Nitsuya** [comment]
？？

**Comment by ne0YT** [comment]
It's already working perfectly, I'll just use the top left button to bring maps to the front
