### ISSUE TITLE
Force shutdown and reboot issue

### ISSUE THREAD

**Issue by ertmuirm** [Nitsuya/AADisplay#2]
When trying to use Google Assistant as the default assistant from the wow.carlauncher.mini interface, my phone undergoes a forced reboot

Here is the command I am using:

am start com.google.android.googlequicksearchbox/com.google.android.apps.gsa.staticplugins.opa.OpaActivity

**Comment by Nitsuya** [comment]
1.如果你要使用自带的Google Assistant, 请删除 [语音助手Shell] 中的内容.
2.如果你要更换启动器, 请在 [首选项包名] 中填写 启动器包名, 不要使用当前手机正在用的启动器
