### ISSUE TITLE
Netflix black screen on virtual display

### ISSUE THREAD

**Issue by ertmuirm** [Nitsuya/AADisplay#3]
When trying to run Netflix on the virtual display mode, videos show up as a black screen due to DRM issues. This is also a known issue on Fermata Auto screen mirror function

Given this app is built specifically in the xposed environment, not sure if this can be addressed by hooking into the right video pipes / widevine, e.g. the Rave app

**Comment by Nitsuya** [comment]
太高端, 不会!  我不是专业的Android开发者, 很多机制不是很了解.

**Comment by ertmuirm** [comment]
理解，谢谢！会继续支持你的应用！
