### ISSUE TITLE
Force close when AADisplay in being used on Android Auto screen and phone screen is touched 

### ISSUE THREAD

**Issue by ertmuirm** [Nitsuya/AADisplay#4]
Phone force closes under the following scenario:
- AADisplay in the foreground on Android Auto head unit, AND
- Phone screen is on, AND
- User interacts with phone screen

**Comment by Nitsuya** [comment]
是的, 三星ROM 给android.app.ITaskStackListener添加了一些特殊的回调事件.
下次反馈问题, 请带上 Rom版本 和 LSP报错日志.
修复该问题是因为其他人给我反馈并提供了LSP日志和framework.jar
