### ISSUE TITLE
侧边栏比例问题

### ISSUE THREAD

**Issue by VT53** [Nitsuya/AADisplay#5]
请问侧边栏比例占据车机画面1/4，需要怎么设定Virtual display Dpi值或是其他设定会比较适合?能请您帮忙说明一下相关参数的作用吗?谢谢

**Comment by Nitsuya** [comment]
如果你未设置dpi 侧边栏占据1/4 这是不正常的情况, 给 图 rom 相关描述!!!!!!!

---

AndroidAutoDpi调整AA自身大小.
VirtualDisplayDpi调整AADisplay显示内容的大小.
侧边栏属于AA,所以应该调整AndroidAutoDpi.
侧边栏宽度是AndroidAuto根据车机屏幕分辨率+dpi计算得出的,如果是6寸480p的屏幕建议设置140,其他分辨率自己调整满意的大小.
因为这个还跟车机的物理尺寸带来的手指触摸面积有关,所以自己试满意的大小.


**Star! Star! Thanks!**
