### ISSUE TITLE
When using AADisplay, launcher won't change scale

### ISSUE THREAD

**Issue by sennpy** [Nitsuya/AADisplay#6]
I chose to use `com.dudu.autoui` since it's from the same maker as in default setting and has english version.

On the phone, the launcher is scaled nicely, but within the virtual display, the launcher looks like it's set to low DPI.

I tried with no DPI setting as well as all sorts of values both higher and lower than what I set for AndroidAutoDpi.

Not sure if it's my phone or that VirtualDisplayDpi isn't working properly. Please help!

Version: 0.14#10.9
Phone: Xiaomi 14 Ultra
ROM: xiaomi.eu hyperOS
Root method: APatch

**Comment by Nitsuya** [comment]
调整手机DPI并在手机上打开，UI也不会发生变化。似乎是应用问题。
