### ISSUE TITLE
AA dpi显示正常，AADISPLAY显示dpi不正确

### ISSUE THREAD

**Issue by eral2001** [Nitsuya/AADisplay#7]
环境：lineageos 21 android14
root: magisk
android auto: AA4MG 
汽车：HONDA

测试过的地图软件：百度地图、百度地图车机版、高德地图等

问题描述：AADISPLAY进入后，百度地图为例，调整VirtualDisplayDpi的数值，数值设置为100，增加或减少都试过。似乎只改变了地图软件的菜单栏大小，地图的区域依旧是非常大。

![Screenshot_20240810-194842_相册](https://github.com/user-attachments/assets/4d7c6019-983c-466a-994b-9d8bbe2c8de1)
![PXL_20240810_183427835 MV](https://github.com/user-attachments/assets/a8a4fb54-1849-45cd-a05d-61f28a777c96)，请帮助解决，已star.

**Comment by Nitsuya** [comment]
杀死应用后 在 虚拟屏中启动应用，请不要在手机上应用并打开移动到虚拟屏，这样会导致孵化时使用手机DPI。

**Comment by eral2001** [comment]
首先感谢这么快就回答我的问题，非常赞！我尝试过在AAdisplay中使用车机桌面软件，此时dpi正常，但是当从AAdisplay环境中车机软件（汽车上）中点击百度地图等软件时就会出现上面的情况。

**Comment by Nitsuya** [comment]
大概率是因为应用使用了ndk获取了application的DPI。在拉起应用的时候我hook了系统层在孵化篡改了JAVA层的application的dpi，ndk我没有思路。。但是我测试是ok的。用高德车机吧。

**Comment by eral2001** [comment]
好的，多谢

**Comment by Nitsuya** [comment]
> 好的，多谢

还有你的AA版本应该高了，所以左边状态栏没有改到，降到12.3。 新版本等我过几天修。

**Comment by eral2001** [comment]
> > 好的，多谢
> 
> 还有你的AA版本应该高了，所以左边状态栏没有改到，降到12.3。 新版本等我过几天修。

好的，已经降级至12.3.642634,明天上车试试。

**Comment by eral2001** [comment]
再次请问一下，如果使用高德车机版，导航时候的转湾标志和限速，道路名称之类的会透传至司机位置前面的屏幕上吗？我看好像有相关代码。

**Comment by Nitsuya** [comment]
> 再次请问一下，如果使用高德车机版，导航时候的转湾标志和限速，道路名称之类的会透传至司机位置前面的屏幕上吗？我看好像有相关代码。

里面确实有测试代码，因为我的仪表盘不支持，所以没做，高德车机会广播消息。欢迎PR.

**Comment by eral2001** [comment]
测试发现，比如。iceraven浏览器,闲鱼，百度地图，高德地图，百度车机版。其他都正常。

**Comment by Nitsuya** [comment]
> 测试发现，下面这几个app会出现菜单界面UI正常，但内容巨大的情况。比如：iceraven浏览器,闲鱼，百度地图，高德地图，百度车机版。其他都正常。

大概率需要修ndk的application的dpi，就将就用吧，ndk我不会修。

**Comment by Nitsuya** [comment]
我测试了高德百度手机版，地图是正常的。我怀疑你没有完全杀死应用并从虚拟屏启动。

**Comment by eral2001** [comment]
> 我测试了高德百度手机版，地图是正常的。我怀疑你没有完全杀死应用并从虚拟屏启动。

我的AAdisplay首选项包名是smart launcher的ginlemon.flowerfree，进入后，通过冰箱启动冻结了的百度地图手机版和高德地图手机版。同时也测试过先解冻并且停止运行app，再次进入。也是这种情况。设置还将首选项包名直接改成百度的也这样。

**Comment by Nitsuya** [comment]
> > 我测试了高德百度手机版，地图是正常的。我怀疑你没有完全杀死应用并从虚拟屏启动。
> 
> 我的AAdisplay首选项包名是smart launcher的ginlemon.flowerfree，进入后，通过冰箱启动冻结了的百度地图手机版和高德地图手机版。同时也测试过先解冻并且停止运行app，再次进入。也是这种情况。设置还将首选项包名直接改成百度的也这样。
> 百度手机版debug的屏幕信息是：screen:large|720*480|density:0.875|densityDpi:140|sw:823|xdpi:140|ydpi:140
> 修改aadisplay可以改变菜单选项等等的大小，但是底图始终是超大。

实际上虚拟屏并没有720p,因为左边AA状态栏占了宽度，你用电脑开个Android模拟器参数设置一样，看看是不是预期一致呢，下个版本我把实际虚拟屏分辨率在映射窗上显示出来。进q群645258581交流。

很多国内应用还有坑就是状态栏预留高度是反射的资源文件。
