### ISSUE TITLE
侧边栏能否适配旋钮

### ISSUE THREAD

**Issue by JasonKwokGJQ** [Nitsuya/AADisplay#8]
使用了AAdisplay后，修改过后的侧边栏不能用车自带的旋钮操控了，其他AA原生的界面能正常操控，虚拟屏应该是不太可能适配旋钮，但是侧边栏应该可以吧？

**Comment by Nitsuya** [comment]
如果车机支持触摸，旋转则没有意义。
如果车机不支持触摸，AAD会变的非常不好使用。
所以现在改成了 旋转 发送 快进/后退 事件，按下 发送 暂停/播放 事件。

**Comment by JasonKwokGJQ** [comment]
谢谢回复。我的车机是既可以触屏，又可以用旋钮控制的。因为屏幕离得比较远，所以正在开车的时候用旋钮比较方便。使用了AADisplay后用旋钮选不中侧边栏的选项，这样不方便使用原生AA界面的时候切换和返回。并不需要在使用虚拟屏的时候用旋钮操作，不知道讲能不能理解到我说的意思？

**Comment by Nitsuya** [comment]
但是AAD是虚拟屏，很难控制焦点，再加上很多应用并不支持，所以不如把旋转按钮做成事件。

**Comment by Nitsuya** [comment]
国内AA自身的应用不是难用就是没法用。去掉状态栏控制AAD又没法控制。
