### ISSUE TITLE
AADisplay constantly force stopping.

### ISSUE THREAD

**Issue by Eclair234** [Nitsuya/AADisplay#9]
I've been using AA Display for about 3 months with no issues. About 5 days ago, it stopped working. I reinstalled it and cleared the AA cache, but it didn't help. The module doesn't start in AA, and opening settings in AA Display crashes the module.  
AA Display - 0.15#12.4+  
AA - 12.6.643244  
Magisk 27000, 
LSPosed 1.9.3_mod (7244) - Zygisk  
AP2A.240905.003  

API version
100

Xposed API call protection
Enabled

Dex Optimizer Wrapper
Supported

Framework version
1.9.3_mod (7244)

Manager package name
com.android.shell

System version
14 (API 34)

Device
Google Google Pixel 7 Pro 

System ABI
arm64-v8a

**Comment by Nitsuya** [comment]
你的描述我无法判断，不工作情况是什么样的？
能否提供模块在LSP下的错误日志。

如果是在AA上无法启动AAD，尝试在[projection.gearhead] properties 中添加以下配置

AppValidation__should_bypass_validation=true

**Comment by Eclair234** [comment]
I cannot access AAD settings, as soon as I tap "setting icon" app crashes.

From the log:   [AAD_AndroidAuoHook] load configPreferences fail
Full log:    https://www.dropbox.com/scl/fi/o68o71mex9ubwq9qpms9o/LSPosed_2024-09-13T13_27_45.350639.zip?rlkey=l0m06b8pmswyweixwhkfiqsdj&dl=0

**Comment by Eclair234** [comment]
resolved

**Comment by Nitsuya** [comment]
没有捐赠渠道..
觉的好用, 请 Start Start Start !!!!!

**Comment by Eclair234** [comment]
Please add donation link.

**Comment by Nitsuya** [comment]
项目首页已添加 捐赠连接，谢谢。

**Comment by Eclair234** [comment]
I donated 350 CNY , I hope you received it. They didn't send me the confirmation. But money is gone from my PayPal. Keep up good work! Thank you

**Comment by Nitsuya** [comment]
感谢捐赠，已收到，谢谢。
